import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/queryProvider";
import NotificationProvider from "@/providers/notifications";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/providers/queryProvider";
import PageHead from "@/components/base/pageHead";
import CartModal from "@/components/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <NotificationProvider>
            <PageHead>{children}</PageHead>
            <CartModal />
          </NotificationProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
